#!/usr/bin/env python3
"""
Convert MAVLink C headers into Cyphal DSDL messages.
Combines MAVPACKED parsing with Lisum dialect support and reg.udral publishers.
"""

from __future__ import annotations
import argparse
import pathlib
import re
import shutil
import sys
from dataclasses import dataclass

# Map C types to Cyphal DSDL types
PRIMITIVE_MAP = {
    'uint8_t': 'saturated uint8',
    'int8_t': 'saturated int8',
    'uint16_t': 'saturated uint16',
    'int16_t': 'saturated int16',
    'uint32_t': 'saturated uint32',
    'int32_t': 'saturated int32',
    'uint64_t': 'saturated uint64',
    'int64_t': 'saturated int64',
    'float': 'float32',
    'double': 'float64',
    'char': 'saturated uint8',
}

RESERVED_NAMES = {"type", "class", "package", "import", "bool"}

# POBOLJŠAN REGEX: Podržava MAVPACKED() strukture
STRUCT_REGEX = re.compile(
    r"typedef\s+struct\s+__mavlink_(?P<name>[a-zA-Z0-9_]+)_t\s*\{(?P<body>.*?)\}\s*mavlink_\1_t;",
    re.DOTALL
)

# POBOLJŠAN REGEX ZA POLJA: Bolje rukovanje razmacima i nizovima
FIELD_REGEX = re.compile(
    r"^\s*(?P<type>[a-z0-9_]+)\s+(?P<name>[a-z0-9_]+)(?:\s*\[(?P<len>\d+)\])?\s*;.*$",
    re.IGNORECASE
)

MSG_ID_REGEX = re.compile(r"#define MAVLINK_MSG_ID_(?P<name>[A-Z0-9_]+)\s+(?P<id>\d+)")
LEN_REGEX = re.compile(r"#define MAVLINK_MSG_ID_(?P<name>[A-Z0-9_]+)_LEN\s+(?P<len>\d+)")

@dataclass
class Field:
    dsdl_type: str
    name: str
    array_len: int | None = None

@dataclass
class Message:
    name: str
    msg_id: int
    payload_len: int | None
    fields: list[Field]

def sanitize_name(name: str) -> str:
    return name + "_" if name in RESERVED_NAMES else name

def camel_case(name_uc: str) -> str:
    return ''.join(p.capitalize() for p in name_uc.lower().split('_'))

def parse_message_header(text: str, filename: str) -> Message | None:
    # 1. Nađi ID i Ime
    msgid_match = MSG_ID_REGEX.search(text)
    if not msgid_match:
        return None
    name_uc = msgid_match.group('name')
    msg_id = int(msgid_match.group('id'))
    
    # 2. Nađi Dužinu
    len_match = LEN_REGEX.search(text)
    payload_len = int(len_match.group('len')) if len_match else 64

    # 3. Očisti text od MAVPACKED makroa da bi regex lakše radio
    clean_text = text.replace("MAVPACKED(", "").replace("})", "}")

    struct_match = STRUCT_REGEX.search(clean_text)
    if not struct_match:
        print(f"Preskačem {filename}: Ne mogu da nađem strukturu", file=sys.stderr)
        return None
        
    fields: list[Field] = []
    for line in struct_match.group('body').splitlines():
        line = line.strip()
        if not line or line.startswith('//'):
            continue
            
        m = FIELD_REGEX.match(line)
        if m:
            c_type = m.group('type')
            if c_type in PRIMITIVE_MAP:
                fields.append(Field(
                    PRIMITIVE_MAP[c_type], 
                    sanitize_name(m.group('name')), 
                    int(m.group('len')) if m.group('len') else None
                ))

    return Message(name_uc, msg_id, payload_len, fields)

def generate_dsdl(message: Message, dialect: str, override_subject_id: int | None = None) -> tuple[str, int]:
    subject_id = override_subject_id if override_subject_id is not None else message.msg_id

    lines = [
        f"# Autogenerated from MAVLink message {message.name}",
        f"# Original MAVLink ID: {message.msg_id}",
        f"# Dialect: {dialect}",
        "",
    ]
    
    for f in message.fields:
        if f.array_len is not None:
            lines.append(f"{f.dsdl_type}[{f.array_len}] {f.name}")
        else:
            lines.append(f"{f.dsdl_type} {f.name}")
    
    lines.append("")
    max_extent_bytes = message.payload_len or 256
    lines.append(f"@extent {max_extent_bytes * 8}")
    lines.append("")

    return '\n'.join(lines), subject_id

def main() -> int:
    ap = argparse.ArgumentParser(description="Convert MAVLink headers to Cyphal DSDL.")
    ap.add_argument(
        '--mavlink-dirs', 
        nargs='+', 
        required=True, 
        help="List of MAVLink C header directories (e.g., common lisum)"
    )
    ap.add_argument('--out-dir', required=True, help="Output root directory for DSDL files")
    ap.add_argument('--emit-reg-publishers', action='store_true', help="Also emit reg.udral publishers helpers")
    args = ap.parse_args()

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0

    root_ns = out_dir / "messages_cyphal_uavcan"
    if root_ns.exists():
        shutil.rmtree(root_ns)
    root_ns.mkdir(parents=True, exist_ok=True)

    MAX_REGULATED_FIXED_SUBJECT_ID = 8191

    for mav_dir in map(pathlib.Path, args.mavlink_dirs):
        if not mav_dir.is_dir():
            print(f"MAVLink dir not found: {mav_dir}", file=sys.stderr)
            continue

        dialect_name = mav_dir.name
        dialect_ns = root_ns / dialect_name
        dialect_ns.mkdir(parents=True, exist_ok=True)

        headers = sorted(mav_dir.glob('mavlink_msg_*.h'))
        if not headers:
            print(f"No MAVLink message headers found in {mav_dir}", file=sys.stderr)
            continue

        # Za Lisum dijalekt: fiksni ID-ovi počinju od 600
        lisum_base = 600
        lisum_counter = 0
        
        for hdr in headers:
            text = hdr.read_text(encoding='utf-8', errors='ignore')
            msg = parse_message_header(text, hdr.name)
            if not msg:
                continue
            
            override_id = None
            if dialect_name.lower() == 'lisum':
                override_id = lisum_base + lisum_counter
                lisum_counter += 1
            
            dsdl_content, subject_id = generate_dsdl(msg, dialect_name, override_subject_id=override_id)
            
            # Za ID-ove <= 8191: koristi numerički prefiks
            # Za ID-ove > 8191: samo ime (bez prefiksa)
            if subject_id <= MAX_REGULATED_FIXED_SUBJECT_ID:
                fname = f"{subject_id}.{camel_case(msg.name)}.1.0.dsdl"
            else:
                fname = f"{camel_case(msg.name)}.1.0.dsdl"
                print(f"INFO: {msg.name} (ID {msg.msg_id}) generisano bez fiksnog ID-ja zbog limita.", file=sys.stderr)
            
            (dialect_ns / fname).write_text(dsdl_content, encoding='utf-8')
            generated += 1

    # Opciono: generisanje reg.udral publisher helper-a
    if args.emit_reg_publishers:
        util_dir = out_dir / "utility"
        util_dir.mkdir(parents=True, exist_ok=True)

        reg_h = util_dir / "cyphal_reg_publishers.h"
        reg_c = util_dir / "cyphal_reg_publishers.c"

        reg_h.write_text(
            """#ifndef CYPHAL_REG_PUBLISHERS_H
#define CYPHAL_REG_PUBLISHERS_H

#include <stddef.h>
#include <stdint.h>

#include "canard.h"

#ifdef __cplusplus
extern "C" {
#endif

// Publish reg.udral.physics.thermodynamics.PressureTempVarTs.0.1 message
int cyphal_publish_reg_pressure_temp_var_ts(
    struct CanardInstance* ins,
    struct CanardTxQueue* txq,
    enum CanardPriority prio,
    const void* payload,
    size_t payload_size,
    CanardTransferID* tid,
    CanardMicrosecond timeout_usec);

#ifdef __cplusplus
}
#endif

#endif // CYPHAL_REG_PUBLISHERS_H
""",
            encoding='utf-8',
        )

        reg_c.write_text(
            """/* Auto-generated Cyphal reg.udral publish helpers. */
#include "cyphal_utility.h"
#include "canard.h"
#include <string.h> 

#include "messages/reg/udral/physics/thermodynamics/PressureTempVarTs_0_1.h"

int cyphal_publish_reg_pressure_temp_var_ts(struct CanardInstance* ins, struct CanardTxQueue* txq, enum CanardPriority prio, const void* payload, size_t payload_size, CanardTransferID* tid, CanardMicrosecond timeout_usec) {
    return cyphal_pub_message(ins, txq, reg_udral_physics_thermodynamics_PressureTempVarTs_0_1_FIXED_PORT_ID_, prio, payload, payload_size, tid, timeout_usec);
}
""",
            encoding='utf-8',
        )

        print(f"Generated reg.udral publishers into {util_dir}")

    print(f"Generated {generated} DSDL files into {out_dir}")
    return 0

if __name__ == '__main__':
    sys.exit(main())