#ifndef DEV_CONFIG_H
#define DEV_CONFIG_H

#define HAL_UART_2_PIN_OPTION 1
#define HAL_UART_3_PIN_OPTION 1

#define LPC_EMAC_ETH_MAX_FLEN 576
#define LPC_EMAC_NUM_RX_FRAG 14
#define LPC_EMAC_NUM_TX_FRAG 14

#define MISSION_PLANNER_UART_TRANSPORT_LAYER 0
#define MISSION_PLANNER_UDP_TRANSPORT_LAYER 1

#endif /* DEV_CONFIG_H */
